name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup show

      - name: Ensure required components
        run: rustup component add rust-src

      - name: Install bpf-linker
        run: cargo install bpf-linker

      - name: Run xtask build
        run: cargo run -p xtask -- build

      - name: Run tests
        run: cargo test --verbose
